# Generated by Django 5.2 on 2025-05-06 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reference_books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Трек-номер"
                    ),
                ),
                (
                    "transport_number",
                    models.CharField(max_length=20, verbose_name="Номер транспорта"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Вес (кг)"
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Объём (м³)",
                    ),
                ),
                ("pickup_address", models.TextField(verbose_name="Адрес забора")),
                ("delivery_address", models.TextField(verbose_name="Адрес доставки")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "scheduled_pickup",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Запланирован забор"
                    ),
                ),
                (
                    "scheduled_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Запланирована доставка"
                    ),
                ),
                (
                    "actual_pickup",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактический забор"
                    ),
                ),
                (
                    "actual_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактическая доставка"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "cargo_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference_books.cargotype",
                        verbose_name="Тип груза",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "packaging_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference_books.packagingtype",
                        verbose_name="Тип упаковки",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True, to="reference_books.service", verbose_name="Услуги"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference_books.deliverystatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference_books.transportmodel",
                        verbose_name="Модель транспорта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка",
                "verbose_name_plural": "Доставки",
                "ordering": ["-created_at"],
            },
        ),
    ]
