# Generated by Django 5.2 on 2025-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_deliverymedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Расстояние (км)",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Итоговая стоимость",
            ),
        ),
    ]
